export const ALL_HOROSCOPES = 'ALL_HOROSCOPES'
export const TODAY = 'TODAY_HOROSCOPE'
export const YESTERDAY = 'YESTERDAY_HOROSCOPE'
export const TOMORROW = 'TOMORROW_HOROSCOPE'

export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'
export const USER = 'USER'

export const ID = 'HOROSCOPE_ID'
export const FIND_ID = 'HOROSCOPE_ID_FROM_DB'
export const FAVORITES = 'FAVORITES'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const TODAY_SIGN = 'TODAY_AND_CLICKED_SIGN'
export const YESTERDAY_SIGN = 'YESTERDAY_SIGN'
export const TOMORROW_SIGN = 'TOMORROW_SIGN'
export const ALL_SIGNS = 'ALL_SIGNS'

